### ISSUE TITLE
Make open data dump public 

### ISSUE THREAD

**Issue by haubourg** [qgis/QGIS-Server-PerfSuite#3]
The pg data dump is fetched from https://github.com/Oslandia/QGIS-Server-PerfSuite/blob/master/docker/data/Dockerfile#L8. 
We should publish it to github too so that contributors can make public pull requests to the database content itself.

**Comment by haubourg** [comment]
The same logic applies to the qgs project and associated resources downloaded by `/scenarios/download.sh` script

**Comment by haubourg** [comment]
I'm wondering if we should embed the minimum dataset and qgs project inside this repository or in a shared repo dedicated to download opendataset for many other projects.

**Comment by pblottiere** [comment]
The data is now embedded in the project.
